# Generated by Django 4.2.2 on 2023-06-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobihivesapp', '0002_classroom_student_classroom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='classroom',
            table='Class Room Table',
        ),
    ]
