# Generated by Django 4.2.2 on 2023-06-08 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobihivesapp', '0004_subject_marksobtained'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksobtained',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student', to='mobihivesapp.student'),
        ),
        migrations.AlterField(
            model_name='marksobtained',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subject', to='mobihivesapp.subject'),
        ),
    ]
