# Generated by Django 4.2.2 on 2023-06-08 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobihivesapp', '0005_alter_marksobtained_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marksobtained',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='marksobtained',
            table='Marks Table',
        ),
    ]
